config/routes.rb
RspecCucumberDemo::Application.routes.draw do
  match 'login', :to => 'users#login'
  resources :users do
    resources :posts
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :posts

  validates_presence_of :title
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :blog
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :blog #has_many later

  accepts_nested_attributes_for :blog
  validates_presence_of :name
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = User.find(params[:user_id]).blog.posts.new
  end

  def create
    User.find(params[:user_id]).blog.posts.create!(params[:post])
    redirect_to user_posts_path
  end

  def index
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @user.build_blog
  end

  def create
    @user = User.create!(params[:user])

    flash[:notice] = 'Welcome. You can now start blogging away!'
    redirect_to user_posts_path(@user.id)
  end

  def index
    @user = User.new
  end

  def login
    user = User.find_by_email(params[:user][:email])
    if user.nil?
      flash[:error] = 'Invalid email'
      redirect_to users_path
    else
      redirect_to user_posts_path(user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.slim
section id='flash'
  = show_flash_messages.html_safe

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RspecCucumberDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'flash' %>
  <%= yield %>
</body>
</html>

app/views/posts/index.html.slim
#title | This is #{@user.name}'s blog #{@user.blog.title}
br
br
| List of posts
br
br
= link_to 'New Post', new_user_post_path
br
br
table{border=1}
  thead
    td ID
    td Title
    td Preview
    td Date created
  tbody
    - if @user.blog.posts.empty?
      tr
        td{colspan=4} No posts here!
    - else
      - @user.blog.posts.each do |p|
        tr
          td = p.id
          td = p.title
          td = p.body
          td = p.created_at

app/views/posts/new.html.slim
= semantic_form_for @post, :url => user_posts_path(@post.blog.user.id), :method => :post do |f|
  = f.input :title
  = f.input :body, :label => 'Post'
  = f.submit 'Post!'

app/views/users/index.html.slim
| Login here!
br
br
= semantic_form_for @user, :url => login_path do |f|
  = f.input :email
  = f.submit 'Login'

app/views/users/new.html.slim
#title Create new User

= semantic_form_for @user do |f|
  = f.input :name
  = f.input :email
  = f.semantic_fields_for :blog do |b|
    = b.input :title, :label => 'Blog'
  = f.submit 'Submit'